// Netlify build step: bundle discovery files into the disco function, and keep non-primary sites out of search indexes.
import fs from 'node:fs';
const files = {
  '/robots.txt': ['robots.txt', 'text/plain; charset=utf-8'],
  '/sitemap.xml': ['sitemap.xml', 'application/xml; charset=utf-8'],
  '/llms.txt': ['llms.txt', 'text/plain; charset=utf-8'],
  '/llms-full.txt': ['llms-full.txt', 'text/plain; charset=utf-8'],
  '/openapi.json': ['openapi.json', 'application/vnd.oai.openapi+json; charset=utf-8'],
  '/blog/feed.xml': ['blog/feed.xml', 'application/rss+xml; charset=utf-8'],
  '/.well-known/api-catalog': ['.well-known/api-catalog', 'application/linkset+json; charset=utf-8']
};
let out = '// Generated by scripts/netlify-build.mjs. Do not edit.\nexport default {\n';
for (const [path, [file, type]] of Object.entries(files)) out += `  ${JSON.stringify(path)}: { type: ${JSON.stringify(type)}, body: ${JSON.stringify(fs.readFileSync(file, 'utf8'))} },\n`;
fs.writeFileSync('lib/discovery-files.mjs', out + '};\n');
const site = process.env.SITE_NAME;
if (site && site !== 'terrace-sun') {
  fs.writeFileSync('_headers', '/*\n  X-Robots-Tag: noindex\n');
  fs.writeFileSync('_redirects', '/account/*  https://terrace-sun.netlify.app/account/:splat  302!\n/account  https://terrace-sun.netlify.app/account/  302!\n');
  console.log(`Site ${site} is a mirror: noindex header written.`);
}
console.log('discovery files bundled:', Object.keys(files).length);
